services:
  database:
    image: postgres:17
    container_name: postgresql
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: vault
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: vault
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vault"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
  vault:
    image: hashicorp/vault:1.19
    container_name: vault
    restart: always
    ports:
      - 8200:8200
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200" # Environment variable to access Vault
    volumes:
      - ./vault.hcl:/vault/config/vault.hcl:ro # Mount your Vault configuration file
    entrypoint: >
      vault server -config=/vault/config/vault.hcl
    cap_add:
      - IPC_LOCK # Required to lock memory for security
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8200/v1/sys/health"]
      interval: 10s
      timeout: 5s
      retries: 5

    depends_on:
      - database
volumes:
  postgres_data: